# Generated by Django 3.2.8 on 2021-10-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('util_civil', models.CharField(choices=[('Mr', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], max_length=4, verbose_name='Civilité')),
                ('util_first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prénom')),
                ('util_last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('util_email', models.EmailField(max_length=254, unique=True, verbose_name='Email @')),
                ('util_phone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='N° Téléphone')),
            ],
        ),
    ]
