# Generated by Django 3.2.8 on 2021-10-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateurs',
            new_name='Utilisateur',
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['util_last_name'], name='I_Utilisateur'),
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.UniqueConstraint(fields=('util_first_name', 'util_last_name'), name='unique_utilisateur'),
        ),
    ]
