# Generated by Django 3.2.8 on 2021-10-12 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_utilisateurs', '0002_auto_20211012_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='util_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='util_is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='util_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
