# Generated by Django 3.2.5 on 2021-07-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pj_ident', models.CharField(max_length=50, verbose_name='Identification')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.AddIndex(
            model_name='piecejointe',
            index=models.Index(fields=['pj_ident'], name='I_pj_ident'),
        ),
        migrations.AddConstraint(
            model_name='piecejointe',
            constraint=models.UniqueConstraint(fields=('pj_ident',), name='Unique_pj_ident'),
        ),
    ]
