# Generated by Django 3.2.5 on 2021-07-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecejointe',
            name='pj_fichier',
            field=models.FileField(default='', upload_to='pj/', verbose_name='Pièce jointe'),
        ),
        migrations.AddConstraint(
            model_name='piecejointe',
            constraint=models.UniqueConstraint(fields=('pj_fichier',), name='Unique_pj_fichier'),
        ),
    ]
